### ISSUE TITLE
Unable to update deployment

### ISSUE THREAD

**Issue by jayme-github** [kelproject/pykube#42]
I tried to change image versions for containers of a deployment.
That breaks with errors like the following:
```
HTTPError: Deployment.extensions "deployment_name" is invalid: spec.template.spec.containers[1].name: Duplicate value: "container_name"
```

I think that jsonpatch creates a broken patch in that case and created [jsonpatch/issue49](https://github.com/stefankoegl/python-json-patch/issues/49) for that.

**Comment by brosner** [comment]
This is a known problem on my end. I have been working to fix this, but it is non-trivial. My timeline is pretty tight on it so expect something this week.

**Comment by jayme-github** [comment]
Any news on this? Maybe there is something one could help with?

**Comment by brosner** [comment]
@jayme-github my apologies. Yes there is something I can get help on. Let me first describe the direction I was going in.

What I would like to see here is a way for us to replicate the "updating" ability of `kubectl apply`. This ultimately results in implementing https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/devel/api-conventions.md#strategic-merge-patch in Python. I have not found anything out there that implements it fully, likely because the changes for Kubernetes are Kubernetes specific and pykube seems to be furthest along in integration. I started some code, but haven't fully tested/completed it.

My code: https://gist.github.com/brosner/842f6c32a958784c037a14cd35a6f3c5
Kubernetes code: https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/util/strategicpatch/patch.go

I would love the extra hands on this.

**Comment by jayme-github** [comment]
After reading through the stuff and writing a bit of `diff_dict` please be lenient with me as I'm new to golangI guess that [LookupPatchMetadata](https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/third_party/forked/json/fields.go#L23) is the tricky part as  it reads `patchStrategy` and `patchMergeKey` from the go structs directly. As those are missing in the API 'till now I'm unsure how we could get them (maybe parse them from go souce at pykube build time?).

my updates at https://gist.github.com/jayme-github/61a052b6d14c9b4f7a6e3bc53c36539d

**Comment by brosner** [comment]
I spent a bit of time today looking into this. While implementing the strategic merge patch would work, I longer think it is the only solution to the problem. The issue, I believe, lies in jsonpatch (as reported by @jayme-github). It really isn't producing the patch I would expect.

**Comment by brosner** [comment]
I have commited my latest work around this particular issue as fb4f46ea6b01e97806d78fcdcdb6b604b0adc479. It has fixed this issue for me.

@jayme-github can you give it a shot? I am going to release 0.12.0 with the change in a few minutes. If there are bugs we can address in 0.12.x.

**Comment by jayme-github** [comment]
Sorry for being late on this @brosner 
I was quite busy last weeks but your fix works at lest for my simple case. Thanks!
